name: Python Build Wheel

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
        config:
          - torch-version: "2.0.1"
            cuda-version: "11.7.1"
            cuda-short: "11.7"
            arch_list: "3.7;3.5+PTX;5.3;5.0;5.2+PTX;6.0;6.1+PTX;7.0+PTX;7.5+PTX;8.0;8.6+PTX"

          - torch-version: "2.0.1"
            cuda-version: "11.8.0"
            cuda-short: "11.8"
            arch_list: "3.7;3.5+PTX;5.3;5.0;5.2+PTX;6.0;6.1+PTX;7.0+PTX;7.5+PTX;8.0;8.6+PTX;8.9+PTX;9.0+PTX"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install pytorch ${{ matrix.config.torch-version }}-cuda${{ matrix.config.cuda-short }}
        run: |
          mamba install -y -c pytorch -c nvidia pytorch torchvision pytorch-cuda=${{ matrix.config.cuda-short }}

      - name: Install build dependencies
        run: mamba install -y setuptools wheel build ninja

      - name: conda clean cache
        run: conda clean -a -y

      - name: Install cuda ${{ matrix.config.cuda-version }}
        run: mamba install -y -c "nvidia/label/cuda-${{ matrix.config.cuda-version }}" cuda

      - name: echo CONDA_PREFIX
        id: conda-preifx
        run: echo "CONDA_PREFIX=${CONDA_PREFIX}" >> "$GITHUB_OUTPUT"

      - name: Build wheel
        env:
          CUDA_HOME: ${{ steps.conda-preifx.outputs.CONDA_PREFIX }}
          TORCH_CUDA_ARCH_LIST: ${{ matrix.config.arch_list }}
        run: |
          python -m build --no-isolation --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.whl
